name: try cache
on: push
jobs:
  cache: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uese: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}
      - run: npm ci 